### ISSUE TITLE
E_Error when accessing wp-admin page

### ISSUE THREAD

**Issue by allinappliadmin** [wp-document-revisions/wp-document-revisions#345]
### Describe the bug

Fatal error is thrown when trying to access /wp-admin page even as administrator

### Steps to reproduce the behavior

1. Go to /wp-admin

### Expected behavior

Access admin pages

### Screenshots
This is the backtrace:
```
Détails de l’erreur
======================
Une erreur de type E_ERROR a été causée dans la ligne 65 du fichier /var/www/vhosts/domain.net/httpdocs/wp-content/plugins/wp-document-revisions/wp-document-revisions.php. Message d’erreur : Uncaught TypeError: Argument 1 passed to str_contains() must be of the type string, null given, called in /var/www/vhosts/domain.net/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Menu.php on line 638 and defined in /var/www/vhosts/domain.net/httpdocs/wp-content/plugins/wp-document-revisions/wp-document-revisions.php:65
Stack trace:
#0 /var/www/vhosts/domain.net/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Menu.php(638): str_contains()
#1 /var/www/vhosts/domain.net/httpdocs/wp-content/uploads/civicrm/ext/theisland/theisland.php(152): CRM_Core_Menu::get()
#2 /var/www/vhosts/domain.net/httpdocs/wp-includes/class-wp-hook.php(287): theisland_body_class()
#3 /var/www/vhosts/domain.net/httpdocs/wp-includes/plugin.php(206): WP_Hook->apply_filters()
#4 /var/www/vhosts/domain.net/httpdocs/wp-admin/admin-header.php(231): apply_filters()
#5 /var/www/vhosts/domain.net/httpdocs/wp-admin/admin.php(239): require_once('/var/www/vhosts...')
#6 {main}
  thrown
```
This is line 68 in code

```
	function str_contains( string $haystack, string $needle ) {
		return empty( $needle ) || strpos( $haystack, $needle ) !== false;
	}

```
### Additional context

WordPress 5.5.14 (yeah I know it's outdated :-/ ) / WP-document-revisions 3.6.0

**Comment by allinappliadmin** [comment]
@NeilWJames thank you for your comprehensive answer. Actually 'theisland' theme wasn't even used so I uninstalled it and also upgraded PHP version to 8.1.xx. which both solved this "issue".
